### PR TITLE
merged Hunter Luisi's repo

### PR DESCRIPTION
**Pull request by brucelane**
updated samples and template

### CODE REVIEW

**Comment by MartinBspheroid** [comment]
I've been  playing around with that fork for time,  but there are aperently some issues according to github, so I have to resolve that first

**Comment by brucelane** [comment]
are you on Mac?
I used it for a while this year, worked fine for me on Windows

**Comment by MartinBspheroid** [comment]
Nope,  on Windows.  there's still some problem with merging and github is
telling me to use command line to sort it out.

I'm in middle of some job and I cannot take a proper look at it. So
probably after weekend.

**Comment by brucelane** [comment]
no hurry! we got plenty of time

**Comment by brucelane** [comment]
well feel free to ignore this PR as it is changing a lot in this block.
I can use my repo for now

**Comment by MartinBspheroid** [comment]
Finaly I have some spare time, so let's dive in :+1:

**Comment by MartinBspheroid** [comment]
Ok,  I took a glance yesterday and decided not to merge, as @hluisi changes are adding some specific code for novation launchpad.  I  would rather keep repo universal for all devices.  But I'm not against having repo with link to complete block for Novation launchpad mentioned in readme.

**Pull request closed without merging**
